apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it-infra@coremaker.io
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.clouddns.projectId }}
          serviceAccountSecretRef:
            name: cert-manager-secrets
            key: cert-manager-service.private-key.json