apiVersion: mesh.cloud.google.com/v1beta1
kind: ControlPlaneRevision
metadata:
  name: {{ .Values.name }}
  annotations:
    mesh.cloud.google.com/vpcsc: "{{ .Values.vpcsc.enabled }}"
  labels:
    mesh.cloud.google.com/managed-cni-enabled: "{{ .Values.cni.enabled }}"
    app.kubernetes.io/created-by: terraform
spec:
  type: {{ .Values.type }}
  channel: {{ .Values.channel }}